### ISSUE TITLE
请问是否可以废弃 @vivaxy/wxml，统一交给你维护？

### ISSUE THREAD

**Issue by vivaxy** [oft/wxml#3]
https://github.com/vivaxy/WXML/issues/30

**Comment by ofzo** [comment]
@vivaxy  @bigmeow 抱歉， 这段时间公司需求比较紧， 没顾上

因为公司的基础工具中使用到了这个项目， 在使用过程中发现的问题以及需要，我单独发布了这个包， 这里感谢 @vivaxy 的贡献

如果可以的话，我们应该一起维护升级， 事实上我的使用过程中还发现一些别的问题， 暂时还在考虑(目前时间也不算多)要不要添加进去

**Comment by vivaxy** [comment]
如果一起维护升级的话，请问你期望的合作方式是？
如果有问题可以提出来，我看看能够帮忙一起解决下。

**Comment by ofzo** [comment]
合作的方式都行

我现在遇到的问题，比如对节点的删减，替换，增加，  对数据绑定的检查等等

**Comment by vivaxy** [comment]
wxml 作为包名更合适，目前包的代码和权限在本仓库。我希望 @vivaxy/wxml 仓库关闭，并指向本仓库。

对节点的删减，替换，增加，对数据绑定的检查是否可以通过 `traverse` + 自定义函数逻辑实现？

**Comment by ofzo** [comment]
我觉得可以

这些功能的实现，还需要提供一些基础功能来支持
